### ISSUE TITLE
2D pulse test case fails

### ISSUE THREAD

**Issue by ctjacobs** [opesci/seigen#6]
As Michael pointed out during my visit, the 2D pulse test case (`tests/pulse/pulse_2d_lf4.py`) now fails with the following error:

```
(firedrake) christian@christian-VirtualBox:~/seigen/tests/pulse$ python pulse_2d_lf4.py 
Number of degrees of freedom: 960000
P-wave velocity: 1.000000
S-wave velocity: 0.500000
Generating inverse mass matrices
Creating solver contexts
t = 0.002500
Traceback (most recent call last):
  File "/home/christian/firedrake/src/PyOP2/pyop2/caching.py", line 197, in __new__
    return cls._cache_lookup(key)
  File "/home/christian/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 52, in _cache_lookup
    return cls._cache.get(key) or cls._read_from_disk(key, comm)
  File "/home/christian/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 72, in _read_from_disk
    raise KeyError("Object with key %s not found" % key)
KeyError: 'Object with key 5ad7ca12e91f4ea00768fd5bbc1cfb76 not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pulse_2d_lf4.py", line 35, in <module>
    elastic.run(T)
  File "/home/christian/seigen/seigen/elastic.py", line 293, in run
    self.solve(self.ctx_stemp, self.invmass_stress, self.stemp)
  File "/home/christian/seigen/seigen/elastic.py", line 364, in solve
    F_a = assemble(rhs)
  File "/home/christian/firedrake/src/firedrake/firedrake/assemble.py", line 99, in assemble
    allocate_only=allocate_only)
  File "<decorator-gen-283>", line 2, in _assemble
  File "/home/christian/firedrake/src/firedrake/firedrake/utils.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/home/christian/firedrake/src/firedrake/firedrake/assemble.py", line 193, in _assemble
    kernels = tsfc_interface.compile_form(f, "form", parameters=form_compiler_parameters, inverse=inverse)
  File "/home/christian/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 195, in compile_form
    number_map).kernels
  File "/home/christian/firedrake/src/PyOP2/pyop2/caching.py", line 199, in __new__
    obj = make_obj()
  File "/home/christian/firedrake/src/PyOP2/pyop2/caching.py", line 189, in make_obj
    obj.__init__(*args, **kwargs)
  File "/home/christian/firedrake/src/firedrake/firedrake/tsfc_interface.py", line 113, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters)
  File "/home/christian/firedrake/src/tsfc/tsfc/driver.py", line 57, in compile_form
    kernel = compile_integral(integral_data, fd, prefix, parameters)
  File "/home/christian/firedrake/src/tsfc/tsfc/driver.py", line 186, in compile_integral
    **config)
  File "/home/christian/firedrake/src/tsfc/tsfc/fem.py", line 418, in compile_ufl
    result = map_expr_dags(translator, expressions)
  File "/home/christian/firedrake/src/ufl/ufl/corealg/map_dag.py", line 86, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/home/christian/firedrake/src/tsfc/tsfc/ufl2gem.py", line 115, in indexed
    return Indexed(aggregate, index)
  File "/home/christian/firedrake/src/tsfc/gem/gem.py", line 49, in __call__
    obj = super(NodeMeta, self).__call__(*args, **kwargs)
  File "/home/christian/firedrake/src/tsfc/gem/gem.py", line 477, in __new__
    index.set_extent(extent)
  File "/home/christian/firedrake/src/tsfc/gem/gem.py", line 409, in set_extent
    raise ValueError("Inconsistent index extents!")
ValueError: Inconsistent index extents!
```

What I think I was trying to do here is solve a 1D equation on a 2D mesh (hence why `dimension` is set to 1). Changing `dimension` to 2 gets rid of the error but the results aren't what I'd expect. I'm tempted to remove this test and just keep the 1D version, as the 2D case doesn't really test much more.

**Comment by FabioLuporini** [comment]
@ctjacobs is this one of the tests you deleted in #7 ?

**Comment by ctjacobs** [comment]
@FabioLuporini It is indeed. We can close this now.
